# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 624b5cb13293f91b03ad36a376fe937876afaf7d5fea3f6fac741b8c7cc23ac47b856d49a4b2e6bbbb36e1040c45eb50ad715c958c441ce15cb33efd668e192e

test:
  secret_key_base: f60049d746fc0f7b2ec6cca40eacd18677ea298ae9c57d10a49757a7133e0e56bee8b7d2a56fcd9fffb2826c403fdab02b6149e06dc607ddaca1ee5310426e4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
